// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mintbapqsdjvuvaxzbfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pbnRiYXBxc2RqdnV2YXh6YmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjAwMjgsImV4cCI6MjA2OTQzNjAyOH0.dnq6Gruzn1onuGzf64_RiZSFI-f6YaWJS-vQbJOmjnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});